version: "3.7"

services:
  mysql_db:
    image: "mysql:8.0"
    restart: always
    environment:
      MYSQL_DATABASE: school_database
      MYSQL_USER: school
      MYSQL_PASSWORD: school
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
      
  school-service:
    image: school-service:1.0
    container_name: school-service
    build:
        context: ../School
        dockerfile: Dockerfile
    ports:
      - '8080:8080' 
    depends_on:
      - mysql_db
    links:
      - mysql_db:app_db
    restart: always


  